# Generated by Django 3.1.1 on 2020-09-15 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('muscle_group', models.CharField(choices=[('CH', 'Chest'), ('BK', 'Back'), ('LG', 'Legs'), ('SH', 'Shoulders'), ('AB', 'Abs'), ('BI', 'Biceps'), ('TR', 'Triceps')], max_length=2)),
                ('target_reps', models.IntegerField(default=10)),
                ('is_timed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkoutGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('day_number', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workouts.workoutgroup')),
            ],
            options={
                'ordering': ('week_number', 'day_number'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('1', 'Beginner'), ('2', 'Standard')], default='1', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('target_reps', models.IntegerField()),
                ('actual_reps', models.IntegerField(default=0)),
                ('percent_of_max', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_sets', to='workouts.workout')),
            ],
            options={
                'ordering': ('set_number',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuxSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('target_reps', models.IntegerField()),
                ('actual_reps', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aux_sets', to='workouts.workout')),
            ],
            options={
                'ordering': ('set_number',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMainLift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_1_rep_max', models.IntegerField()),
                ('increment', models.IntegerField()),
                ('aux_muscle_group1', models.CharField(blank=True, choices=[('CH', 'Chest'), ('BK', 'Back'), ('LG', 'Legs'), ('SH', 'Shoulders'), ('AB', 'Abs'), ('BI', 'Biceps'), ('TR', 'Triceps')], max_length=2, null=True)),
                ('aux_muscle_group2', models.CharField(blank=True, choices=[('CH', 'Chest'), ('BK', 'Back'), ('LG', 'Legs'), ('SH', 'Shoulders'), ('AB', 'Abs'), ('BI', 'Biceps'), ('TR', 'Triceps')], max_length=2, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_lifts', to='workouts.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'exercise')},
            },
        ),
    ]
